# Final NumPy Assignment (Classes 1–4)

### Instructions
- Solve all questions.
- Write your code in the code cell below each question.
- Do not modify the questions.
- Total Questions: **30**


# Part A – Array Creation

### Q1. Create a NumPy array from the list `[5,10,15,20,25]`.

In [2]:
# Write your answer here
import numpy as np
arr = np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


### Q2. Create a **3×4** array of zeros.

In [3]:
# Write your answer here
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Q3. Create a **4×4** array of ones.

In [4]:
# Write your answer here
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Q4. Create a **5×5 identity matrix** using `np.eye()`.

In [5]:
# Write your answer here
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Q5. Create an array from **1 to 50** with a step of **5**.

In [9]:
# Write your answer here
np.arange(1,51,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

# Part B – Array Attributes

### Q6. Find the **shape** of the given array.

In [10]:
# Write your answer here
np.shape(arr)

(5,)

### Q7. Find the **number of dimensions (`ndim`)**.

In [11]:
# Write your answer here
np.ndim(arr)

1

### Q8. Find the **total number of elements (`size`)**.

In [12]:
# Write your answer here
np.size(arr)

5

### Q9. Find the **data type (`dtype`)**.

In [14]:
arr.dtype

dtype('int64')

### Q10. Convert the array into **float** datatype.

In [16]:
# Write your answer here
arr
arr.astype(float)

array([ 5., 10., 15., 20., 25.])

# Part C – Indexing & Slicing

### Q11. Print the **first element** of a 1D array.

In [19]:
# Write your answer here
arr[0]

np.int64(5)

### Q12. Print the **last element** of a 1D array.

In [20]:
# Write your answer here
arr[4]

np.int64(25)

### Q13. Print the **first row** of a 2D array.

In [23]:
# Write your answer here
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0]
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Q14. Print the **last column** of a 2D array.

In [26]:
# Write your answer here
arr[0 :,2]

array([3, 6, 9])

### Q15. Print elements from **index 2 to 7**.

In [27]:
# Write your answer here
arr[2:7]

array([[7, 8, 9]])

### Q16. Reverse the array using slicing.

In [28]:
# Write your answer here
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# Part D – Reshape & Flatten

### Q17. Convert a 1D array of **12 elements** into a **3×4** matrix.

In [34]:
a = np.arange(1, 13)
b = a.reshape(3, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q18. Reshape the above matrix into **2×6**.

In [35]:
# Write your answer here
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Q19. Flatten the matrix using `flatten()`.

In [37]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Q20. Reshape the array into **4×3**.

In [38]:
# Write your answer here
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Part E – Broadcasting & Arithmetic

### Q21. Add **10** to every element of an array.

In [39]:
# Write your answer here
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Q22. Multiply every element by **5**.

In [40]:
# Write your answer here
arr *5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Q23. Add two arrays element-wise.

In [51]:
# Write your answer here
arr1 = np.array([[1,2,3],[3,4,7]])
arr2 = np.array([[4,5,6],[4,9,2]])
print(arr1.sum(axis =1))
print(arr2.sum(axis=0))

[ 6 14]
[ 8 14  8]


### Q24. Find the square of every element.

In [52]:
# Write your answer here
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Part F – Fancy & Boolean Indexing

### Q25. Using fancy indexing, print **20, 40, 80** from a 1D array.

In [53]:
# Write your answer here
arr =np.array([10,20,30,40,50,60,70,80])
arr[[1,3,7]]

array([20, 40, 80])

### Q26. Using fancy indexing, print the **first and third rows** of a 2D array.

In [59]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

### Q27. Using boolean indexing, print elements **greater than 20**.

In [60]:
# Write your answer here
arr = np.array([10,20,30,40,50,60,70,80])
arr[arr>20]

array([30, 40, 50, 60, 70, 80])

### Q28. Using boolean indexing, print only the **even numbers**.

In [61]:
# Write your answer here
arr[arr%2==0]

array([10, 20, 30, 40, 50, 60, 70, 80])

# Part G – Sorting & Concatenation

### Q29. Sort an array using `np.sort()`.

In [68]:
# Write your answer here
arr = np.array([2,7,4,6,0])
np.sort(arr)

array([0, 2, 4, 6, 7])

### Q30. Find the sorted indices using `np.argsort()`.

In [69]:
# Write your answer here
np.argsort(arr)

array([4, 0, 2, 3, 1])

### Q31. Join two arrays using `np.concatenate()`.

In [70]:
# Write your answer here
a = np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])